spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
server:
  port: 8080
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
