spring:
  datasource:
    username: jiem
    password: jiem
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.112.107:3306/blog
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
server:
  port: 8081
#mybatis:
#  mapper-locations: classpath:mapper/*.xml

# MinIO文件系统
minio:
  url: http://101.35.112.107:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: blog